
version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: Table
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1qazxsw2L*
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  app:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./my-app/.env
    environment:
      DATABASE_URL: postgresql://postgres:1qazxsw2L*@db:5432/Table?schema=public
volumes:
  postgres_data: